= Zish

A data serialization format, designed to be an improvement on JSON. It adds
timestamp, decimal and binary types, as well as multi-line strings.

* File extension `.zish`
* MIME type `application/zish` (suggested, not official or anything)


== Zish Format

Here's an example of Zish:

```
// This is a comment

// Curly brackets delimit a map
{
  "title": "A Hero of Our Time",  // A key / value pair of strings
  "description": null,
  "key": 'a3NoaGdybA==',  // Single quotes delimit base64 encoded binary
  "number_of_novellas": 5,
  "price": 7.99,  // A decimal (lossless) number
  "read_date": 2017-07-16T14:05:00Z,
  "tags": [  // Square brackets delimit a list
    "russian",
    "novel",
    "19th century"],
  "weight": 6.88e0,  // A float (lossy) number
  "would_recommend": true}
```

Timestamp::
  Follows the https://tools.ietf.org/rfc/rfc3339.txt[RFC3339] format.

The https://github.com/tlocke/zish/blob/master/zish/antlr/Zish.g4[formal
specification] of Zish is an http://www.antlr.org/[ANTLR] grammar.


== Motivation

https://en.wikipedia.org/wiki/JSON[JSON] is wildly popular, but it lacks some
primitive data types:

* Timestamp
* Decimal (exact https://en.wikipedia.org/wiki/Decimal_data_type[decimal]
  number)
* Binary (a string of bytes) 

Zish has these types, in addition to the JSON types.

=== Why not just use Amazon Ion?

Zish is heavily influenced by https://amzn.github.io/ion-docs/index.html[Amazon
Ion], but Ion has the following shortcomings as a replacement for JSON:

* Ion doesn't have a map type, instead it has a struct type which allows
  duplicate keys.
* Ion has data types such as '`symbol`', s-expressions, and '`keyword`' which
  aren't commonly needed.
* There are three text types in Ion, which may be confusing.
* There are two binary data types.

That's not to say isn't an excellent format, this is just evaluating it as an
improvement on JSON.


=== Why not just use the edn format?

Like Amazon Ion, https://github.com/edn-format/edn[edn] has more features than
is necessary for an improved JSON. In particular:

* It's extensible, ie. it has a mechanism for user defined types.
* Edn has types such as '`character`', '`symbol`', '`vector`' which may not be
  needed.
* The timestamp type isn't a first-class type, it's added in as an extension.

Again, this isn't to be derogatory about edn, it's just evaluating it as a
replacement to JSON.


== Python Implementation

A Python 3 library for the Zish format, released under the
https://github.com/tlocke/zish/blob/master/LICENSE[MIT Licence].

image:https://travis-ci.org/tlocke/zish.svg?branch=master["Build Status",
link="https://travis-ci.org/tlocke/zish"]


== Installation

It's a good idea to set up a virtualenv:

 virtualenv venv
 source venv/bin/activate

then install Zish with pip:

 pip install zish


== Quickstart

To go from a Python object to an Zish string use `zish.dumps`. To go from an
Zish string to a Python object use `zish.loads`. Eg.

....
>>> from zish import loads, dumps
>>> from datetime import datetime, timezone
>>> from decimal import Decimal
>>>
>>> # Take a Python object
>>> book = {
...     'title': 'A Hero of Our Time',
...     'read_date': datetime(2017, 7, 16, 14, 5, tzinfo=timezone.utc),
...     'would_recommend': True,
...     'description': None,
...     'number_of_novellas': 5,
...     'price': Decimal('7.99'),
...     'weight': 6.88,
...     'key': bytearray(b'kshhgrl'),
...     'tags': ['russian', 'novel', '19th century']}
>>>
>>> # Output it as an Zish string
>>> zish_str = dumps(book)
>>> print(zish_str)
{
  "description": null,
  "key": 'a3NoaGdybA==',
  "number_of_novellas": 5,
  "price": 7.99,
  "read_date": 2017-07-16T14:05:00Z,
  "tags": [
    "russian",
    "novel",
    "19th century"],
  "title": "A Hero of Our Time",
  "weight": 6.88,
  "would_recommend": true}
>>>
>>> # Load the Zish string, to give us back the Python object
>>> reloaded_book = loads(zish_str)
>>> 
>>> # Print the title
>>> print(reloaded_book['title'])
A Hero of Our Time

....


== Release Notes


=== Version 0.0.2 (2017-08-05)

* Now uses RFC3339 for timestamps.


=== Version 0.0.1 (2017-08-03)

* Fix bug where an EOF could cause an infinite loop.


=== Version 0.0.0 (2017-08-01)

* First public release. Passes all the tests.


== Contributing

Useful links:

* http://www.antlr.org/api/Java/index.html?overview-summary.html[ANTLR JavaDocs]

To run the tests:

* Change to the `zish` directory: `cd zish`
* Create a virtual environment: `virtualenv --python=python3 venv`
* Activate the virtual environment: `source venv/bin/activate`
* Install tox: `pip install tox`
* Run tox: `tox`

The core parser is created using https://github.com/antlr/antlr4[ANTLR] from
the Zish grammar. To create the parser files, go to the `antlr` directory and
download the ANTLR jar and then run the following command:

 java -jar antlr-4.7-complete.jar -Dlanguage=Python3 Zish.g4


=== Making A New Release

Run `tox` to make sure all tests pass, then update the `Release Notes` section
then do:

....
git tag -a x.y.z -m "version x.y.z"
python setup.py register sdist bdist_wheel upload --sign
....
