= Zish
:toc: preamble

A data serialization format, designed to be an improvement on JSON. It adds
timestamp, decimal and binary types, as well as multi-line strings.

* File extension `.zish`
* MIME type `application/x.zish`


== Zish Format

Here's an example of Zish:

```
// This is a comment

// Curly brackets delimit a map
{
  "title": "A Hero of Our Time",  // A key / value pair of strings
  "description": null,
  "key": 'a3NoaGdybA==',  // Single quotes delimit base64 encoded binary
  "number_of_novellas": 5,
  "price": 7.99,  // A decimal (lossless) number
  "read_date": 2017-07-16T14:05:00Z,
  "tags": [  // Square brackets delimit a list
    "russian",
    "novel",
    "19th century"],
  "weight": 6.88e0,  // A float (lossy) number
  "would_recommend": true}
```

Zish is a valid stream of Unicode code points encoded in UTF-8. The
https://github.com/tlocke/zish/blob/master/zish/antlr/Zish.g4[formal
specification of Zish] is an http://www.antlr.org/[ANTLR] grammar. Zish has the
following data types:


=== Timestamp

Follows the https://tools.ietf.org/rfc/rfc3339.txt[RFC3339] format. Eg.
`2017-08-09T10:40:09Z`, `2017-08-09T10:40:09.037Z`.


=== String

Strings are sequences of Unicode characters and are delimited by a
double-quote character `"`, and can contain line breaks. If you need to write
a string that contains a `"` then escape it with a backslash by doing `\"`.
There are other escapes allowed in strings. Here's the full list:

|===
| Escape | Description | ASCII Hex Value

| `\a`
| Alert (beep sound)
| 07

| `\b`
| Backspace
| 08

| `\t`
| Horizontal tab
| 09

| `\n`
| Linefeed
| 0A

| `\v`
| Virtical tab
| 0B

| `\f`
| Formfeed
| 0C

| `\r`
| Carriage return
| 0D

| `\"`
| Double quotation mark
| 22

| `\\`
| Backslash
| 5C

| `\` followed by either a Carriage Return or Linefeed, or
  Carriage Return then Linefeed.
| A backslash before a newline sequence is a way to remove a newline.
|

| `\u` followed by four hex digits.
| A unicode code point.
|

| `\U` followed by eight hex digits.
| A unicode code point.
|

| 
|===


=== Bytes

Binary data is delimited by the single-quote character, and represented by a
base64 encoding as specified by
https://tools.ietf.org/html/rfc3548.html[RFC3548]. Eg. `'a3NoaGdybA=='`.


=== Integer

Integers can't begin with a `+`, and integers with more than one digit can't
begin with a zero. Examples of valid integers are: +

* `0`
* `-0`
* `389`
* `-589`


=== Decimal

A https://en.wikipedia.org/wiki/Decimal_data_type[decimal] is a lossless
representation of a real number. The exponent starts with a `d`. Examples are:

* `0.993`
* `1.78d-1`


=== Float

A lossy representation of a real number. The exponent starts with an `e`. It
can have the special values `+inf`, `-inf` and `nan`. Examples are:

* `-0.7e4`
* `3.141e0`


=== List

A https://en.wikipedia.org/wiki/List_(abstract_data_type)[list] is an ordered
sequence of values, where the same value may occur more than once. Lists
begin with a `[` and end with a `]` and the values are separated by `,`. An
example is: `[56, "pod", 0]`. An element of a list can be any Zish type
including a list or map.


=== Map

A https://en.wikipedia.org/wiki/Associative_array[map] is an unordered
collection of key / value pairs. Duplicate keys aren't allowed. Maps start
with a `{` and end with a `}`. The pairs are separated by a `,` and the key
is separated from the value with a `:`. The value part of a pair can be any
Zish type, and the key part of a pair can be any Zish type except the container
types (map, list and set). An example of a map is:
`{"hello": 90, true: "larch", 5: [null]}`.


=== Set

A https://en.wikipedia.org/wiki/Set_(abstract_data_type)[set] is an unordered
collection of values, with no duplicates. Sets start with a `(` and end with a
`)`. The values are separated by a `,`. A value can be of any Zish type. An
example of a set is: `(-7, "Ahoy!", null)`.


=== Comments

Inline comments start with `//` and block comments begin with `/*` and end with
`*/`. Comments are treated as whitespace rather than values, so they're
ignored by the parser and not passed through to the application. In XML,
comments are passed through to the application, which is thought to lead to an
abuse of comments because it's unclear whether they're part of the content or
not. JSON https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr[avoids
this problem] by not allowing comments. Zish steers a middle path here by
allowing comments, but ignoring them at the parsing stage.


== Why Zish?

https://en.wikipedia.org/wiki/JSON[JSON] is wildly popular, but it lacks some
primitive data types:

* Timestamp
* Decimal (exact https://en.wikipedia.org/wiki/Decimal_data_type[decimal]
  number)
* Binary (a string of bytes) 

Zish has these types, in addition to the JSON types. It's also possible to have
multi-line strings in Zish, which JSON doesn't allow.

To see where Zish falls in the space of data serialization formats, here's a
comparison with the text representation of Amazon Ion and also the edn data
format.


=== Comparison with Amazon Ion

Zish is influenced by the text representation of
https://amzn.github.io/ion-docs/index.html[Amazon Ion], but there are several
differences between them:

* Ion doesn't have a map type, instead it has a struct type which allows
  duplicate keys.
* Ion has data types such as '`symbol`', s-expressions, and '`keyword`' which
  Zish doesn't have.
* There are three text types in Ion, but Zish just has one.
* There are two binary data types in Ion, but Zish just has one.
* Ion has a binary as well as text representation.


=== Comparison with the edn format

Zish is close in spirit to https://github.com/edn-format/edn[edn] but again
there are differences:

* Edn is extensible, ie. it has a mechanism for user defined types.
* Edn has types such as '`character`', '`symbol`' and '`vector`' which Zish
  doesn't have.


== Python Implementation

A Python 3 library for the Zish format, released under the
https://github.com/tlocke/zish/blob/master/LICENSE[MIT Licence].

image:https://travis-ci.org/tlocke/zish.svg?branch=master["Build Status",
link="https://travis-ci.org/tlocke/zish"]


=== Installation

It's a good idea to set up a virtualenv:

 virtualenv venv
 source venv/bin/activate

then install Zish with pip:

 pip install zish


=== Quickstart

To go from a Python object to an Zish string use `zish.dumps`. To go from an
Zish string to a Python object use `zish.loads`. Eg.

....
>>> from zish import loads, dumps
>>> from datetime import datetime, timezone
>>> from decimal import Decimal
>>>
>>> # Take a Python object
>>> book = {
...     'title': 'A Hero of Our Time',
...     'read_date': datetime(2017, 7, 16, 14, 5, tzinfo=timezone.utc),
...     'would_recommend': True,
...     'description': None,
...     'number_of_novellas': 5,
...     'price': Decimal('7.99'),
...     'weight': 6.88,
...     'key': b'kshhgrl',
...     'tags': ['russian', 'novel', '19th century']}
>>>
>>> # Output it as an Zish string
>>> zish_str = dumps(book)
>>> print(zish_str)
{
  "description": null,
  "key": 'a3NoaGdybA==',
  "number_of_novellas": 5,
  "price": 7.99,
  "read_date": 2017-07-16T14:05:00Z,
  "tags": [
    "russian",
    "novel",
    "19th century"],
  "title": "A Hero of Our Time",
  "weight": 6.88e0,
  "would_recommend": true}
>>>
>>> # Load the Zish string, to give us back the Python object
>>> reloaded_book = loads(zish_str)
>>> 
>>> # Print the title
>>> print(reloaded_book['title'])
A Hero of Our Time

....

.Python to Zish type mapping
|===
| Python Type | Zish Type

| bool
| bool

| int
| integer

| str
| string

| datetime.datetime
| timestamp

| dict
| map

| decimal.Decimal
| decimal

| float
| float

| bytearray, bytes
| bytes

| list, tuple
| list
|===


=== Release Notes


==== Version 0.0.8 (2017-08-24)

* Container types aren't allowed as map keys.
* Performance improvements.


==== Version 0.0.7 (2017-08-22)

* Fix bug with UTC timestamp formatting.


==== Version 0.0.6 (2017-08-22)

* Fix bug in timestamp formatting.
* Add note about comments.


==== Version 0.0.5 (2017-08-18)

* Fix bug where `dumps` fails for a `tuple`.


==== Version 0.0.4 (2017-08-15)

* Simplify integer types.


==== Version 0.0.3 (2017-08-09)

* Fixed bug where interpreter couldn't find the `zish.antlr` package in eggs.
* Removed a few superfluous escape sequences.


==== Version 0.0.2 (2017-08-05)

* Now uses RFC3339 for timestamps.


==== Version 0.0.1 (2017-08-03)

* Fix bug where an EOF could cause an infinite loop.


==== Version 0.0.0 (2017-08-01)

* First public release. Passes all the tests.


=== Contributing

Useful links:

* http://www.antlr.org/api/Java/index.html?overview-summary.html[ANTLR JavaDocs]

To run the tests:

* Change to the `zish` directory: `cd zish`
* Create a virtual environment: `virtualenv --python=python3 venv`
* Activate the virtual environment: `source venv/bin/activate`
* Install tox: `pip install tox`
* Run tox: `tox`

The core parser is created using https://github.com/antlr/antlr4[ANTLR] from
the Zish grammar. To create the parser files, go to the `antlr` directory and
download the ANTLR jar and then run the following command:

 java -jar antlr-4.7-complete.jar -Dlanguage=Python3 Zish.g4


==== Making A New Release

Run `tox` to make sure all tests pass, then update the `Release Notes` section
then do:

....
git tag -a x.y.z -m "version x.y.z"
python setup.py sdist bdist_wheel upload --sign
....
